export const WELCOME = 'WELCOME';

// Interest actions
export const GET_INTEREST = 'GET_INTEREST';
export const GET_INTEREST_SUCCESS = 'GET_INTEREST_SUCCESS';
export const GET_INTEREST_ERROR = 'GET_INTEREST_ERROR';

// Commerces actions
export const GET_COMMERCES = 'GET_COMMERCES';
export const GET_COMMERCES_SUCCESS = 'GET_COMMERCES_SUCCESS';
export const GET_COMMERCES_ERROR = 'GET_COMMERCES_ERROR';

export const GET_COMMERCES_BY_INTEREST = 'GET_COMMERCES_BY_INTEREST';
export const GET_COMMERCES_BY_INTEREST_SUCCESS = 'GET_COMMERCES_BY_INTEREST_SUCCESS';
export const GET_COMMERCES_BY_INTEREST_ERROR = 'GET_COMMERCES_BY_INTEREST_ERROR';

// Discount actions
export const GET_DISCOUNT = 'GET_DISCOUNT';
export const GET_DISCOUNT_SUCCESS = 'GET_DISCOUNT_SUCCESS';
export const GET_DISCOUNT_ERROR = 'GET_DISCOUNT_ERROR';

// QR actions
export const CREATE_QR = 'CREATE_QR';
export const CREATE_QR_SUCCESS = 'CREATE_QR_SUCCESS';
export const CREATE_QR_ERROR = 'CREATE_QR_ERROR';

export const GET_QR_BY_ID = 'GET_QR_BY_ID';
export const GET_QR_BY_ID_SUCCESS = 'GET_QR_BY_ID_SUCCESS';
export const GET_QR_BY_ID_ERROR = 'GET_QR_BY_ID_ERROR';

export const GET_LIST_OF_QRS = 'GET_LIST_OF_QRS';
export const GET_LIST_OF_QRS_SUCCESS = 'GET_LIST_OF_QRS_SUCCESS';
export const GET_LIST_OF_QRS_ERROR = 'GET_LIST_OF_QRS_ERROR';
